### ISSUE TITLE
Documentation (How to make your own VCS guide) appears to be gone.

### ISSUE THREAD

**Issue by CarrieKami** [MSathieu/SimpleVCS#22]
Hey! 

I had been following the guide you had put up, but recently it seems to have been taken down. Would it be possible for you to put it back up?  It has been very helpful in terms of learning more on VCS and learning how to build one on my own. 

Thanks for your time! :)

**Comment by MSathieu** [comment]
I took it down because I thought there was no interest in it after some time. When I took it down I thought I still had backups on my computer, but I'm afraid I lost those too. Sorry

**Comment by MSathieu** [comment]
I've asked Github support if they could restore it though.

**Comment by MSathieu** [comment]
The repository is restored and the book can be found at https://msathieu.gitbooks.io/make-a-version-control-system/content/

**Comment by CarrieKami** [comment]
@MSathieu Sorry for replying so late....Thanks so much! The book is a big help :)
